// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Clients  string
	Projects string
	Roles    string
	Tasks    string
	Tenants  string
}{
	Clients:  "clients",
	Projects: "projects",
	Roles:    "roles",
	Tasks:    "tasks",
	Tenants:  "tenants",
}
