// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
	"gopkg.in/volatiletech/null.v6"
)

// Project is an object representing the database table.
type Project struct {
	ID         int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	TenantID   int       `boil:"tenant_id" json:"tenant_id" toml:"tenant_id" yaml:"tenant_id"`
	ClientID   int       `boil:"client_id" json:"client_id" toml:"client_id" yaml:"client_id"`
	ParentID   null.Int  `boil:"parent_id" json:"parent_id,omitempty" toml:"parent_id" yaml:"parent_id,omitempty"`
	Name       string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	Slug       string    `boil:"slug" json:"slug" toml:"slug" yaml:"slug"`
	StartsOn   null.Time `boil:"starts_on" json:"starts_on,omitempty" toml:"starts_on" yaml:"starts_on,omitempty"`
	EndsOn     null.Time `boil:"ends_on" json:"ends_on,omitempty" toml:"ends_on" yaml:"ends_on,omitempty"`
	IsActive   bool      `boil:"is_active" json:"is_active" toml:"is_active" yaml:"is_active"`
	IsBillable bool      `boil:"is_billable" json:"is_billable" toml:"is_billable" yaml:"is_billable"`
	CreatedAt  time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt  time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *projectR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L projectL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ProjectColumns = struct {
	ID         string
	TenantID   string
	ClientID   string
	ParentID   string
	Name       string
	Slug       string
	StartsOn   string
	EndsOn     string
	IsActive   string
	IsBillable string
	CreatedAt  string
	UpdatedAt  string
}{
	ID:         "id",
	TenantID:   "tenant_id",
	ClientID:   "client_id",
	ParentID:   "parent_id",
	Name:       "name",
	Slug:       "slug",
	StartsOn:   "starts_on",
	EndsOn:     "ends_on",
	IsActive:   "is_active",
	IsBillable: "is_billable",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
}

// projectR is where relationships are stored.
type projectR struct {
	Tenant         *Tenant
	Client         *Client
	Parent         *Project
	ParentProjects ProjectSlice
	Tasks          TaskSlice
}

// projectL is where Load methods for each relationship are stored.
type projectL struct{}

var (
	projectColumns               = []string{"id", "tenant_id", "client_id", "parent_id", "name", "slug", "starts_on", "ends_on", "is_active", "is_billable", "created_at", "updated_at"}
	projectColumnsWithoutDefault = []string{"tenant_id", "client_id", "parent_id", "starts_on", "ends_on"}
	projectColumnsWithDefault    = []string{"id", "name", "slug", "is_active", "is_billable", "created_at", "updated_at"}
	projectPrimaryKeyColumns     = []string{"id"}
)

type (
	// ProjectSlice is an alias for a slice of pointers to Project.
	// This should generally be used opposed to []Project.
	ProjectSlice []*Project
	// ProjectHook is the signature for custom Project hook methods
	ProjectHook func(boil.Executor, *Project) error

	projectQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	projectType                 = reflect.TypeOf(&Project{})
	projectMapping              = queries.MakeStructMapping(projectType)
	projectPrimaryKeyMapping, _ = queries.BindMapping(projectType, projectMapping, projectPrimaryKeyColumns)
	projectInsertCacheMut       sync.RWMutex
	projectInsertCache          = make(map[string]insertCache)
	projectUpdateCacheMut       sync.RWMutex
	projectUpdateCache          = make(map[string]updateCache)
	projectUpsertCacheMut       sync.RWMutex
	projectUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var projectBeforeInsertHooks []ProjectHook
var projectBeforeUpdateHooks []ProjectHook
var projectBeforeDeleteHooks []ProjectHook
var projectBeforeUpsertHooks []ProjectHook

var projectAfterInsertHooks []ProjectHook
var projectAfterSelectHooks []ProjectHook
var projectAfterUpdateHooks []ProjectHook
var projectAfterDeleteHooks []ProjectHook
var projectAfterUpsertHooks []ProjectHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Project) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range projectBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Project) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range projectBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Project) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range projectBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Project) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range projectBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Project) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range projectAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Project) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range projectAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Project) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range projectAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Project) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range projectAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Project) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range projectAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddProjectHook registers your hook function for all future operations.
func AddProjectHook(hookPoint boil.HookPoint, projectHook ProjectHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		projectBeforeInsertHooks = append(projectBeforeInsertHooks, projectHook)
	case boil.BeforeUpdateHook:
		projectBeforeUpdateHooks = append(projectBeforeUpdateHooks, projectHook)
	case boil.BeforeDeleteHook:
		projectBeforeDeleteHooks = append(projectBeforeDeleteHooks, projectHook)
	case boil.BeforeUpsertHook:
		projectBeforeUpsertHooks = append(projectBeforeUpsertHooks, projectHook)
	case boil.AfterInsertHook:
		projectAfterInsertHooks = append(projectAfterInsertHooks, projectHook)
	case boil.AfterSelectHook:
		projectAfterSelectHooks = append(projectAfterSelectHooks, projectHook)
	case boil.AfterUpdateHook:
		projectAfterUpdateHooks = append(projectAfterUpdateHooks, projectHook)
	case boil.AfterDeleteHook:
		projectAfterDeleteHooks = append(projectAfterDeleteHooks, projectHook)
	case boil.AfterUpsertHook:
		projectAfterUpsertHooks = append(projectAfterUpsertHooks, projectHook)
	}
}

// OneP returns a single project record from the query, and panics on error.
func (q projectQuery) OneP() *Project {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single project record from the query.
func (q projectQuery) One() (*Project, error) {
	o := &Project{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for projects")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all Project records from the query, and panics on error.
func (q projectQuery) AllP() ProjectSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Project records from the query.
func (q projectQuery) All() (ProjectSlice, error) {
	var o []*Project

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Project slice")
	}

	if len(projectAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all Project records in the query, and panics on error.
func (q projectQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Project records in the query.
func (q projectQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count projects rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q projectQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q projectQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if projects exists")
	}

	return count > 0, nil
}

// TenantG pointed to by the foreign key.
func (o *Project) TenantG(mods ...qm.QueryMod) tenantQuery {
	return o.Tenant(boil.GetDB(), mods...)
}

// Tenant pointed to by the foreign key.
func (o *Project) Tenant(exec boil.Executor, mods ...qm.QueryMod) tenantQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.TenantID),
	}

	queryMods = append(queryMods, mods...)

	query := Tenants(exec, queryMods...)
	queries.SetFrom(query.Query, "\"tenants\"")

	return query
}

// ClientG pointed to by the foreign key.
func (o *Project) ClientG(mods ...qm.QueryMod) clientQuery {
	return o.Client(boil.GetDB(), mods...)
}

// Client pointed to by the foreign key.
func (o *Project) Client(exec boil.Executor, mods ...qm.QueryMod) clientQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.ClientID),
	}

	queryMods = append(queryMods, mods...)

	query := Clients(exec, queryMods...)
	queries.SetFrom(query.Query, "\"clients\"")

	return query
}

// ParentG pointed to by the foreign key.
func (o *Project) ParentG(mods ...qm.QueryMod) projectQuery {
	return o.Parent(boil.GetDB(), mods...)
}

// Parent pointed to by the foreign key.
func (o *Project) Parent(exec boil.Executor, mods ...qm.QueryMod) projectQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.ParentID),
	}

	queryMods = append(queryMods, mods...)

	query := Projects(exec, queryMods...)
	queries.SetFrom(query.Query, "\"projects\"")

	return query
}

// ParentProjectsG retrieves all the project's projects via parent_id column.
func (o *Project) ParentProjectsG(mods ...qm.QueryMod) projectQuery {
	return o.ParentProjects(boil.GetDB(), mods...)
}

// ParentProjects retrieves all the project's projects with an executor via parent_id column.
func (o *Project) ParentProjects(exec boil.Executor, mods ...qm.QueryMod) projectQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"projects\".\"parent_id\"=?", o.ID),
	)

	query := Projects(exec, queryMods...)
	queries.SetFrom(query.Query, "\"projects\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"projects\".*"})
	}

	return query
}

// TasksG retrieves all the task's tasks.
func (o *Project) TasksG(mods ...qm.QueryMod) taskQuery {
	return o.Tasks(boil.GetDB(), mods...)
}

// Tasks retrieves all the task's tasks with an executor.
func (o *Project) Tasks(exec boil.Executor, mods ...qm.QueryMod) taskQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"tasks\".\"project_id\"=?", o.ID),
	)

	query := Tasks(exec, queryMods...)
	queries.SetFrom(query.Query, "\"tasks\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"tasks\".*"})
	}

	return query
}

// LoadTenant allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (projectL) LoadTenant(e boil.Executor, singular bool, maybeProject interface{}) error {
	var slice []*Project
	var object *Project

	count := 1
	if singular {
		object = maybeProject.(*Project)
	} else {
		slice = *maybeProject.(*[]*Project)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &projectR{}
		}
		args[0] = object.TenantID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &projectR{}
			}
			args[i] = obj.TenantID
		}
	}

	query := fmt.Sprintf(
		"select * from \"tenants\" where \"id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Tenant")
	}
	defer results.Close()

	var resultSlice []*Tenant
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Tenant")
	}

	if len(projectAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.Tenant = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.TenantID == foreign.ID {
				local.R.Tenant = foreign
				break
			}
		}
	}

	return nil
}

// LoadClient allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (projectL) LoadClient(e boil.Executor, singular bool, maybeProject interface{}) error {
	var slice []*Project
	var object *Project

	count := 1
	if singular {
		object = maybeProject.(*Project)
	} else {
		slice = *maybeProject.(*[]*Project)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &projectR{}
		}
		args[0] = object.ClientID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &projectR{}
			}
			args[i] = obj.ClientID
		}
	}

	query := fmt.Sprintf(
		"select * from \"clients\" where \"id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Client")
	}
	defer results.Close()

	var resultSlice []*Client
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Client")
	}

	if len(projectAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.Client = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ClientID == foreign.ID {
				local.R.Client = foreign
				break
			}
		}
	}

	return nil
}

// LoadParent allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (projectL) LoadParent(e boil.Executor, singular bool, maybeProject interface{}) error {
	var slice []*Project
	var object *Project

	count := 1
	if singular {
		object = maybeProject.(*Project)
	} else {
		slice = *maybeProject.(*[]*Project)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &projectR{}
		}
		args[0] = object.ParentID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &projectR{}
			}
			args[i] = obj.ParentID
		}
	}

	query := fmt.Sprintf(
		"select * from \"projects\" where \"id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Project")
	}
	defer results.Close()

	var resultSlice []*Project
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Project")
	}

	if len(projectAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.Parent = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ParentID.Int == foreign.ID {
				local.R.Parent = foreign
				break
			}
		}
	}

	return nil
}

// LoadParentProjects allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (projectL) LoadParentProjects(e boil.Executor, singular bool, maybeProject interface{}) error {
	var slice []*Project
	var object *Project

	count := 1
	if singular {
		object = maybeProject.(*Project)
	} else {
		slice = *maybeProject.(*[]*Project)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &projectR{}
		}
		args[0] = object.ID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &projectR{}
			}
			args[i] = obj.ID
		}
	}

	query := fmt.Sprintf(
		"select * from \"projects\" where \"parent_id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load projects")
	}
	defer results.Close()

	var resultSlice []*Project
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice projects")
	}

	if len(projectAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ParentProjects = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.ParentID.Int {
				local.R.ParentProjects = append(local.R.ParentProjects, foreign)
				break
			}
		}
	}

	return nil
}

// LoadTasks allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (projectL) LoadTasks(e boil.Executor, singular bool, maybeProject interface{}) error {
	var slice []*Project
	var object *Project

	count := 1
	if singular {
		object = maybeProject.(*Project)
	} else {
		slice = *maybeProject.(*[]*Project)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &projectR{}
		}
		args[0] = object.ID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &projectR{}
			}
			args[i] = obj.ID
		}
	}

	query := fmt.Sprintf(
		"select * from \"tasks\" where \"project_id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load tasks")
	}
	defer results.Close()

	var resultSlice []*Task
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice tasks")
	}

	if len(taskAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Tasks = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.ProjectID {
				local.R.Tasks = append(local.R.Tasks, foreign)
				break
			}
		}
	}

	return nil
}

// SetTenantG of the project to the related item.
// Sets o.R.Tenant to related.
// Adds o to related.R.Projects.
// Uses the global database handle.
func (o *Project) SetTenantG(insert bool, related *Tenant) error {
	return o.SetTenant(boil.GetDB(), insert, related)
}

// SetTenantP of the project to the related item.
// Sets o.R.Tenant to related.
// Adds o to related.R.Projects.
// Panics on error.
func (o *Project) SetTenantP(exec boil.Executor, insert bool, related *Tenant) {
	if err := o.SetTenant(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetTenantGP of the project to the related item.
// Sets o.R.Tenant to related.
// Adds o to related.R.Projects.
// Uses the global database handle and panics on error.
func (o *Project) SetTenantGP(insert bool, related *Tenant) {
	if err := o.SetTenant(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetTenant of the project to the related item.
// Sets o.R.Tenant to related.
// Adds o to related.R.Projects.
func (o *Project) SetTenant(exec boil.Executor, insert bool, related *Tenant) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"projects\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"tenant_id"}),
		strmangle.WhereClause("\"", "\"", 2, projectPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.TenantID = related.ID

	if o.R == nil {
		o.R = &projectR{
			Tenant: related,
		}
	} else {
		o.R.Tenant = related
	}

	if related.R == nil {
		related.R = &tenantR{
			Projects: ProjectSlice{o},
		}
	} else {
		related.R.Projects = append(related.R.Projects, o)
	}

	return nil
}

// SetClientG of the project to the related item.
// Sets o.R.Client to related.
// Adds o to related.R.Projects.
// Uses the global database handle.
func (o *Project) SetClientG(insert bool, related *Client) error {
	return o.SetClient(boil.GetDB(), insert, related)
}

// SetClientP of the project to the related item.
// Sets o.R.Client to related.
// Adds o to related.R.Projects.
// Panics on error.
func (o *Project) SetClientP(exec boil.Executor, insert bool, related *Client) {
	if err := o.SetClient(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetClientGP of the project to the related item.
// Sets o.R.Client to related.
// Adds o to related.R.Projects.
// Uses the global database handle and panics on error.
func (o *Project) SetClientGP(insert bool, related *Client) {
	if err := o.SetClient(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetClient of the project to the related item.
// Sets o.R.Client to related.
// Adds o to related.R.Projects.
func (o *Project) SetClient(exec boil.Executor, insert bool, related *Client) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"projects\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"client_id"}),
		strmangle.WhereClause("\"", "\"", 2, projectPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ClientID = related.ID

	if o.R == nil {
		o.R = &projectR{
			Client: related,
		}
	} else {
		o.R.Client = related
	}

	if related.R == nil {
		related.R = &clientR{
			Projects: ProjectSlice{o},
		}
	} else {
		related.R.Projects = append(related.R.Projects, o)
	}

	return nil
}

// SetParentG of the project to the related item.
// Sets o.R.Parent to related.
// Adds o to related.R.ParentProjects.
// Uses the global database handle.
func (o *Project) SetParentG(insert bool, related *Project) error {
	return o.SetParent(boil.GetDB(), insert, related)
}

// SetParentP of the project to the related item.
// Sets o.R.Parent to related.
// Adds o to related.R.ParentProjects.
// Panics on error.
func (o *Project) SetParentP(exec boil.Executor, insert bool, related *Project) {
	if err := o.SetParent(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetParentGP of the project to the related item.
// Sets o.R.Parent to related.
// Adds o to related.R.ParentProjects.
// Uses the global database handle and panics on error.
func (o *Project) SetParentGP(insert bool, related *Project) {
	if err := o.SetParent(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetParent of the project to the related item.
// Sets o.R.Parent to related.
// Adds o to related.R.ParentProjects.
func (o *Project) SetParent(exec boil.Executor, insert bool, related *Project) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"projects\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"parent_id"}),
		strmangle.WhereClause("\"", "\"", 2, projectPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ParentID.Int = related.ID
	o.ParentID.Valid = true

	if o.R == nil {
		o.R = &projectR{
			Parent: related,
		}
	} else {
		o.R.Parent = related
	}

	if related.R == nil {
		related.R = &projectR{
			ParentProjects: ProjectSlice{o},
		}
	} else {
		related.R.ParentProjects = append(related.R.ParentProjects, o)
	}

	return nil
}

// RemoveParentG relationship.
// Sets o.R.Parent to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Uses the global database handle.
func (o *Project) RemoveParentG(related *Project) error {
	return o.RemoveParent(boil.GetDB(), related)
}

// RemoveParentP relationship.
// Sets o.R.Parent to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Panics on error.
func (o *Project) RemoveParentP(exec boil.Executor, related *Project) {
	if err := o.RemoveParent(exec, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveParentGP relationship.
// Sets o.R.Parent to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Uses the global database handle and panics on error.
func (o *Project) RemoveParentGP(related *Project) {
	if err := o.RemoveParent(boil.GetDB(), related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveParent relationship.
// Sets o.R.Parent to nil.
// Removes o from all passed in related items' relationships struct (Optional).
func (o *Project) RemoveParent(exec boil.Executor, related *Project) error {
	var err error

	o.ParentID.Valid = false
	if err = o.Update(exec, "parent_id"); err != nil {
		o.ParentID.Valid = true
		return errors.Wrap(err, "failed to update local table")
	}

	o.R.Parent = nil
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.ParentProjects {
		if o.ParentID.Int != ri.ParentID.Int {
			continue
		}

		ln := len(related.R.ParentProjects)
		if ln > 1 && i < ln-1 {
			related.R.ParentProjects[i] = related.R.ParentProjects[ln-1]
		}
		related.R.ParentProjects = related.R.ParentProjects[:ln-1]
		break
	}
	return nil
}

// AddParentProjectsG adds the given related objects to the existing relationships
// of the project, optionally inserting them as new records.
// Appends related to o.R.ParentProjects.
// Sets related.R.Parent appropriately.
// Uses the global database handle.
func (o *Project) AddParentProjectsG(insert bool, related ...*Project) error {
	return o.AddParentProjects(boil.GetDB(), insert, related...)
}

// AddParentProjectsP adds the given related objects to the existing relationships
// of the project, optionally inserting them as new records.
// Appends related to o.R.ParentProjects.
// Sets related.R.Parent appropriately.
// Panics on error.
func (o *Project) AddParentProjectsP(exec boil.Executor, insert bool, related ...*Project) {
	if err := o.AddParentProjects(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddParentProjectsGP adds the given related objects to the existing relationships
// of the project, optionally inserting them as new records.
// Appends related to o.R.ParentProjects.
// Sets related.R.Parent appropriately.
// Uses the global database handle and panics on error.
func (o *Project) AddParentProjectsGP(insert bool, related ...*Project) {
	if err := o.AddParentProjects(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddParentProjects adds the given related objects to the existing relationships
// of the project, optionally inserting them as new records.
// Appends related to o.R.ParentProjects.
// Sets related.R.Parent appropriately.
func (o *Project) AddParentProjects(exec boil.Executor, insert bool, related ...*Project) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.ParentID.Int = o.ID
			rel.ParentID.Valid = true
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"projects\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"parent_id"}),
				strmangle.WhereClause("\"", "\"", 2, projectPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.ParentID.Int = o.ID
			rel.ParentID.Valid = true
		}
	}

	if o.R == nil {
		o.R = &projectR{
			ParentProjects: related,
		}
	} else {
		o.R.ParentProjects = append(o.R.ParentProjects, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &projectR{
				Parent: o,
			}
		} else {
			rel.R.Parent = o
		}
	}
	return nil
}

// SetParentProjectsG removes all previously related items of the
// project replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Parent's ParentProjects accordingly.
// Replaces o.R.ParentProjects with related.
// Sets related.R.Parent's ParentProjects accordingly.
// Uses the global database handle.
func (o *Project) SetParentProjectsG(insert bool, related ...*Project) error {
	return o.SetParentProjects(boil.GetDB(), insert, related...)
}

// SetParentProjectsP removes all previously related items of the
// project replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Parent's ParentProjects accordingly.
// Replaces o.R.ParentProjects with related.
// Sets related.R.Parent's ParentProjects accordingly.
// Panics on error.
func (o *Project) SetParentProjectsP(exec boil.Executor, insert bool, related ...*Project) {
	if err := o.SetParentProjects(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetParentProjectsGP removes all previously related items of the
// project replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Parent's ParentProjects accordingly.
// Replaces o.R.ParentProjects with related.
// Sets related.R.Parent's ParentProjects accordingly.
// Uses the global database handle and panics on error.
func (o *Project) SetParentProjectsGP(insert bool, related ...*Project) {
	if err := o.SetParentProjects(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetParentProjects removes all previously related items of the
// project replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Parent's ParentProjects accordingly.
// Replaces o.R.ParentProjects with related.
// Sets related.R.Parent's ParentProjects accordingly.
func (o *Project) SetParentProjects(exec boil.Executor, insert bool, related ...*Project) error {
	query := "update \"projects\" set \"parent_id\" = null where \"parent_id\" = $1"
	values := []interface{}{o.ID}
	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err := exec.Exec(query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.ParentProjects {
			rel.ParentID.Valid = false
			if rel.R == nil {
				continue
			}

			rel.R.Parent = nil
		}

		o.R.ParentProjects = nil
	}
	return o.AddParentProjects(exec, insert, related...)
}

// RemoveParentProjectsG relationships from objects passed in.
// Removes related items from R.ParentProjects (uses pointer comparison, removal does not keep order)
// Sets related.R.Parent.
// Uses the global database handle.
func (o *Project) RemoveParentProjectsG(related ...*Project) error {
	return o.RemoveParentProjects(boil.GetDB(), related...)
}

// RemoveParentProjectsP relationships from objects passed in.
// Removes related items from R.ParentProjects (uses pointer comparison, removal does not keep order)
// Sets related.R.Parent.
// Panics on error.
func (o *Project) RemoveParentProjectsP(exec boil.Executor, related ...*Project) {
	if err := o.RemoveParentProjects(exec, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveParentProjectsGP relationships from objects passed in.
// Removes related items from R.ParentProjects (uses pointer comparison, removal does not keep order)
// Sets related.R.Parent.
// Uses the global database handle and panics on error.
func (o *Project) RemoveParentProjectsGP(related ...*Project) {
	if err := o.RemoveParentProjects(boil.GetDB(), related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveParentProjects relationships from objects passed in.
// Removes related items from R.ParentProjects (uses pointer comparison, removal does not keep order)
// Sets related.R.Parent.
func (o *Project) RemoveParentProjects(exec boil.Executor, related ...*Project) error {
	var err error
	for _, rel := range related {
		rel.ParentID.Valid = false
		if rel.R != nil {
			rel.R.Parent = nil
		}
		if err = rel.Update(exec, "parent_id"); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.ParentProjects {
			if rel != ri {
				continue
			}

			ln := len(o.R.ParentProjects)
			if ln > 1 && i < ln-1 {
				o.R.ParentProjects[i] = o.R.ParentProjects[ln-1]
			}
			o.R.ParentProjects = o.R.ParentProjects[:ln-1]
			break
		}
	}

	return nil
}

// AddTasksG adds the given related objects to the existing relationships
// of the project, optionally inserting them as new records.
// Appends related to o.R.Tasks.
// Sets related.R.Project appropriately.
// Uses the global database handle.
func (o *Project) AddTasksG(insert bool, related ...*Task) error {
	return o.AddTasks(boil.GetDB(), insert, related...)
}

// AddTasksP adds the given related objects to the existing relationships
// of the project, optionally inserting them as new records.
// Appends related to o.R.Tasks.
// Sets related.R.Project appropriately.
// Panics on error.
func (o *Project) AddTasksP(exec boil.Executor, insert bool, related ...*Task) {
	if err := o.AddTasks(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddTasksGP adds the given related objects to the existing relationships
// of the project, optionally inserting them as new records.
// Appends related to o.R.Tasks.
// Sets related.R.Project appropriately.
// Uses the global database handle and panics on error.
func (o *Project) AddTasksGP(insert bool, related ...*Task) {
	if err := o.AddTasks(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddTasks adds the given related objects to the existing relationships
// of the project, optionally inserting them as new records.
// Appends related to o.R.Tasks.
// Sets related.R.Project appropriately.
func (o *Project) AddTasks(exec boil.Executor, insert bool, related ...*Task) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.ProjectID = o.ID
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"tasks\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"project_id"}),
				strmangle.WhereClause("\"", "\"", 2, taskPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.ProjectID = o.ID
		}
	}

	if o.R == nil {
		o.R = &projectR{
			Tasks: related,
		}
	} else {
		o.R.Tasks = append(o.R.Tasks, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &taskR{
				Project: o,
			}
		} else {
			rel.R.Project = o
		}
	}
	return nil
}

// ProjectsG retrieves all records.
func ProjectsG(mods ...qm.QueryMod) projectQuery {
	return Projects(boil.GetDB(), mods...)
}

// Projects retrieves all the records using an executor.
func Projects(exec boil.Executor, mods ...qm.QueryMod) projectQuery {
	mods = append(mods, qm.From("\"projects\""))
	return projectQuery{NewQuery(exec, mods...)}
}

// FindProjectG retrieves a single record by ID.
func FindProjectG(id int, selectCols ...string) (*Project, error) {
	return FindProject(boil.GetDB(), id, selectCols...)
}

// FindProjectGP retrieves a single record by ID, and panics on error.
func FindProjectGP(id int, selectCols ...string) *Project {
	retobj, err := FindProject(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindProject retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindProject(exec boil.Executor, id int, selectCols ...string) (*Project, error) {
	projectObj := &Project{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"projects\" where \"id\"=$1", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(projectObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from projects")
	}

	return projectObj, nil
}

// FindProjectP retrieves a single record by ID with an executor, and panics on error.
func FindProjectP(exec boil.Executor, id int, selectCols ...string) *Project {
	retobj, err := FindProject(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Project) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Project) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Project) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *Project) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no projects provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	if o.UpdatedAt.IsZero() {
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(projectColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	projectInsertCacheMut.RLock()
	cache, cached := projectInsertCache[key]
	projectInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			projectColumns,
			projectColumnsWithDefault,
			projectColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(projectType, projectMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(projectType, projectMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"projects\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"projects\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into projects")
	}

	if !cached {
		projectInsertCacheMut.Lock()
		projectInsertCache[key] = cache
		projectInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single Project record. See Update for
// whitelist behavior description.
func (o *Project) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single Project record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *Project) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the Project, and panics on error.
// See Update for whitelist behavior description.
func (o *Project) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the Project.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *Project) Update(exec boil.Executor, whitelist ...string) error {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	projectUpdateCacheMut.RLock()
	cache, cached := projectUpdateCache[key]
	projectUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			projectColumns,
			projectPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update projects, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"projects\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, projectPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(projectType, projectMapping, append(wl, projectPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update projects row")
	}

	if !cached {
		projectUpdateCacheMut.Lock()
		projectUpdateCache[key] = cache
		projectUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q projectQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q projectQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for projects")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o ProjectSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o ProjectSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o ProjectSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ProjectSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), projectPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"projects\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, projectPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in project slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Project) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Project) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Project) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *Project) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no projects provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	o.UpdatedAt = currTime

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(projectColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	projectUpsertCacheMut.RLock()
	cache, cached := projectUpsertCache[key]
	projectUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			projectColumns,
			projectColumnsWithDefault,
			projectColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			projectColumns,
			projectPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert projects, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(projectPrimaryKeyColumns))
			copy(conflict, projectPrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"projects\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(projectType, projectMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(projectType, projectMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert projects")
	}

	if !cached {
		projectUpsertCacheMut.Lock()
		projectUpsertCache[key] = cache
		projectUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single Project record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Project) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single Project record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Project) DeleteG() error {
	if o == nil {
		return errors.New("models: no Project provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single Project record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Project) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single Project record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Project) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Project provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), projectPrimaryKeyMapping)
	sql := "DELETE FROM \"projects\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from projects")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q projectQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q projectQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no projectQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from projects")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o ProjectSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o ProjectSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no Project slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o ProjectSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ProjectSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Project slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(projectBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), projectPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"projects\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, projectPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from project slice")
	}

	if len(projectAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Project) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Project) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Project) ReloadG() error {
	if o == nil {
		return errors.New("models: no Project provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Project) Reload(exec boil.Executor) error {
	ret, err := FindProject(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *ProjectSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *ProjectSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ProjectSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty ProjectSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ProjectSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	projects := ProjectSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), projectPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"projects\".* FROM \"projects\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, projectPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&projects)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ProjectSlice")
	}

	*o = projects

	return nil
}

// ProjectExists checks if the Project row exists.
func ProjectExists(exec boil.Executor, id int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"projects\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if projects exists")
	}

	return exists, nil
}

// ProjectExistsG checks if the Project row exists.
func ProjectExistsG(id int) (bool, error) {
	return ProjectExists(boil.GetDB(), id)
}

// ProjectExistsGP checks if the Project row exists. Panics on error.
func ProjectExistsGP(id int) bool {
	e, err := ProjectExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// ProjectExistsP checks if the Project row exists. Panics on error.
func ProjectExistsP(exec boil.Executor, id int) bool {
	e, err := ProjectExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
